"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const German_1 = require("./German");
const CityName_1 = require("@civ-clone/core-civilization/CityName");
const CityNameRegistry_1 = require("@civ-clone/core-civilization/CityNameRegistry");
[
    'Berlin',
    'Hamburg',
    'Munich',
    'Cologne',
    'Frankfurt',
    'Stuttgart',
    'Düsseldorf',
    'Dortmund',
    'Essen',
    'Leipzig',
    'Bremen',
    'Dresden',
    'Hanover',
    'Nuremberg',
    'Duisburg',
    'Bochum',
    'Wuppertal',
    'Bielefeld',
    'Bonn',
    'Münster',
    'Karlsruhe',
    'Mannheim',
    'Augsburg',
    'Wiesbaden',
    'Gelsenkirchen',
    'Mönchengladbach',
    'Braunschweig',
    'Chemnitz',
    'Kiel',
    'Aachen',
    'Halle',
    'Magdeburg',
    'Freiburg',
    'Krefeld',
    'Lübeck',
    'Oberhausen',
    'Erfurt',
    'Mainz',
    'Rostock',
    'Kassel',
    'Hagen',
    'Hamm',
    'Saarbrücken',
    'Mülheim an der Ruhr',
    'Potsdam',
    'Ludwigshafen am Rhein',
    'Oldenburg',
    'Leverkusen',
    'Osnabrück',
    'Solingen',
].forEach((name, i) => CityNameRegistry_1.instance.register(new CityName_1.default(name, German_1.default, i === 0)));
//# sourceMappingURL=registerCityNames.js.map